### ISSUE TITLE
Issue-initializes the repo

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#2]
Automated Review Comments
Issues in back-end/.env:
  - (2, 'Line exceeds 80 characters')
Issues in back-end/middleware/auth.js:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in back-end/models/User.js:
  - (2, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in back-end/package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Line exceeds 80 characters')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Line exceeds 80 characters')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (240, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (249, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (261, 'Hardcoded string found')
  - (262, 'Line exceeds 80 characters')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Line exceeds 80 characters')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Line exceeds 80 characters')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Line exceeds 80 characters')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Line exceeds 80 characters')
  - (335, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Line exceeds 80 characters')
  - (347, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Line exceeds 80 characters')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Line exceeds 80 characters')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (393, 'Hardcoded string found')
  - (394, 'Line exceeds 80 characters')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (402, 'Line exceeds 80 characters')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Line exceeds 80 characters')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Line exceeds 80 characters')
  - (430, 'Hardcoded string found')
  - (431, 'Line exceeds 80 characters')
  - (431, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Line exceeds 80 characters')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (453, 'Line exceeds 80 characters')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (464, 'Line exceeds 80 characters')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Line exceeds 80 characters')
  - (474, 'Hardcoded string found')
  - (475, 'Line exceeds 80 characters')
  - (475, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (489, 'Hardcoded string found')
  - (490, 'Line exceeds 80 characters')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Line exceeds 80 characters')
  - (501, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Line exceeds 80 characters')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (513, 'Line exceeds 80 characters')
  - (513, 'Hardcoded string found')
  - (514, 'Line exceeds 80 characters')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (528, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Line exceeds 80 characters')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (545, 'Line exceeds 80 characters')
  - (545, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Line exceeds 80 characters')
  - (554, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Line exceeds 80 characters')
  - (561, 'Hardcoded string found')
  - (562, 'Line exceeds 80 characters')
  - (562, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (566, 'Line exceeds 80 characters')
  - (566, 'Hardcoded string found')
  - (567, 'Line exceeds 80 characters')
  - (567, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Line exceeds 80 characters')
  - (571, 'Hardcoded string found')
  - (572, 'Line exceeds 80 characters')
  - (572, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Line exceeds 80 characters')
  - (576, 'Hardcoded string found')
  - (577, 'Line exceeds 80 characters')
  - (577, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Line exceeds 80 characters')
  - (581, 'Hardcoded string found')
  - (582, 'Line exceeds 80 characters')
  - (582, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Line exceeds 80 characters')
  - (586, 'Hardcoded string found')
  - (587, 'Line exceeds 80 characters')
  - (587, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Line exceeds 80 characters')
  - (591, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (592, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Line exceeds 80 characters')
  - (596, 'Hardcoded string found')
  - (597, 'Line exceeds 80 characters')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (604, 'Line exceeds 80 characters')
  - (604, 'Hardcoded string found')
  - (605, 'Line exceeds 80 characters')
  - (605, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Line exceeds 80 characters')
  - (609, 'Hardcoded string found')
  - (610, 'Line exceeds 80 characters')
  - (610, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (615, 'Line exceeds 80 characters')
  - (615, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (623, 'Line exceeds 80 characters')
  - (623, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (627, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Line exceeds 80 characters')
  - (634, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Line exceeds 80 characters')
  - (641, 'Hardcoded string found')
  - (642, 'Line exceeds 80 characters')
  - (642, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (651, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (653, 'Line exceeds 80 characters')
  - (653, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (660, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (673, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (697, 'Line exceeds 80 characters')
  - (697, 'Hardcoded string found')
  - (698, 'Line exceeds 80 characters')
  - (698, 'Hardcoded string found')
  - (699, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (707, 'Line exceeds 80 characters')
  - (707, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (710, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (712, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (718, 'Hardcoded string found')
  - (720, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (727, 'Hardcoded string found')
  - (728, 'Line exceeds 80 characters')
  - (728, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (734, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (736, 'Line exceeds 80 characters')
  - (736, 'Hardcoded string found')
  - (737, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (741, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Line exceeds 80 characters')
  - (747, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (751, 'Line exceeds 80 characters')
  - (751, 'Hardcoded string found')
  - (752, 'Line exceeds 80 characters')
  - (752, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (758, 'Hardcoded string found')
  - (759, 'Line exceeds 80 characters')
  - (759, 'Hardcoded string found')
  - (760, 'Line exceeds 80 characters')
  - (760, 'Hardcoded string found')
  - (761, 'Hardcoded string found')
  - (762, 'Hardcoded string found')
  - (766, 'Hardcoded string found')
  - (767, 'Line exceeds 80 characters')
  - (767, 'Hardcoded string found')
  - (768, 'Line exceeds 80 characters')
  - (768, 'Hardcoded string found')
  - (769, 'Hardcoded string found')
  - (770, 'Hardcoded string found')
  - (772, 'Hardcoded string found')
  - (773, 'Hardcoded string found')
  - (777, 'Hardcoded string found')
  - (778, 'Line exceeds 80 characters')
  - (778, 'Hardcoded string found')
  - (779, 'Line exceeds 80 characters')
  - (779, 'Hardcoded string found')
  - (780, 'Hardcoded string found')
  - (783, 'Hardcoded string found')
  - (784, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (789, 'Hardcoded string found')
  - (790, 'Line exceeds 80 characters')
  - (790, 'Hardcoded string found')
  - (791, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (797, 'Line exceeds 80 characters')
  - (797, 'Hardcoded string found')
  - (798, 'Line exceeds 80 characters')
  - (798, 'Hardcoded string found')
  - (801, 'Hardcoded string found')
  - (802, 'Line exceeds 80 characters')
  - (802, 'Hardcoded string found')
  - (803, 'Line exceeds 80 characters')
  - (803, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (805, 'Hardcoded string found')
  - (808, 'Hardcoded string found')
  - (809, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (815, 'Line exceeds 80 characters')
  - (815, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (817, 'Hardcoded string found')
  - (821, 'Hardcoded string found')
  - (822, 'Hardcoded string found')
  - (823, 'Line exceeds 80 characters')
  - (823, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (827, 'Hardcoded string found')
  - (828, 'Hardcoded string found')
  - (830, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (835, 'Hardcoded string found')
  - (836, 'Line exceeds 80 characters')
  - (836, 'Hardcoded string found')
  - (837, 'Line exceeds 80 characters')
  - (837, 'Hardcoded string found')
  - (838, 'Hardcoded string found')
  - (839, 'Hardcoded string found')
  - (843, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (845, 'Line exceeds 80 characters')
  - (845, 'Hardcoded string found')
  - (846, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (850, 'Hardcoded string found')
  - (852, 'Hardcoded string found')
  - (853, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Line exceeds 80 characters')
  - (858, 'Hardcoded string found')
  - (859, 'Line exceeds 80 characters')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (862, 'Hardcoded string found')
  - (863, 'Hardcoded string found')
  - (866, 'Hardcoded string found')
  - (867, 'Hardcoded string found')
  - (870, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (877, 'Line exceeds 80 characters')
  - (877, 'Hardcoded string found')
  - (878, 'Line exceeds 80 characters')
  - (878, 'Hardcoded string found')
  - (881, 'Hardcoded string found')
  - (882, 'Hardcoded string found')
  - (883, 'Line exceeds 80 characters')
  - (883, 'Hardcoded string found')
  - (884, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (892, 'Hardcoded string found')
  - (893, 'Hardcoded string found')
  - (894, 'Line exceeds 80 characters')
  - (894, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (896, 'Hardcoded string found')
  - (897, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (904, 'Hardcoded string found')
  - (905, 'Hardcoded string found')
  - (908, 'Hardcoded string found')
  - (910, 'Hardcoded string found')
  - (911, 'Hardcoded string found')
  - (915, 'Hardcoded string found')
  - (916, 'Hardcoded string found')
  - (917, 'Line exceeds 80 characters')
  - (917, 'Hardcoded string found')
  - (918, 'Hardcoded string found')
  - (919, 'Hardcoded string found')
  - (923, 'Hardcoded string found')
  - (924, 'Hardcoded string found')
  - (925, 'Line exceeds 80 characters')
  - (925, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (929, 'Line exceeds 80 characters')
  - (929, 'Hardcoded string found')
  - (930, 'Line exceeds 80 characters')
  - (930, 'Hardcoded string found')
  - (931, 'Hardcoded string found')
  - (932, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (935, 'Hardcoded string found')
  - (937, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
  - (943, 'Line exceeds 80 characters')
  - (943, 'Hardcoded string found')
  - (944, 'Line exceeds 80 characters')
  - (944, 'Hardcoded string found')
  - (945, 'Hardcoded string found')
  - (950, 'Hardcoded string found')
  - (953, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (958, 'Hardcoded string found')
  - (959, 'Line exceeds 80 characters')
  - (959, 'Hardcoded string found')
  - (960, 'Line exceeds 80 characters')
  - (960, 'Hardcoded string found')
  - (963, 'Hardcoded string found')
  - (964, 'Line exceeds 80 characters')
  - (964, 'Hardcoded string found')
  - (965, 'Line exceeds 80 characters')
  - (965, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (972, 'Hardcoded string found')
  - (973, 'Hardcoded string found')
  - (975, 'Hardcoded string found')
  - (976, 'Hardcoded string found')
  - (980, 'Hardcoded string found')
  - (981, 'Hardcoded string found')
  - (982, 'Line exceeds 80 characters')
  - (982, 'Hardcoded string found')
  - (985, 'Hardcoded string found')
  - (986, 'Line exceeds 80 characters')
  - (986, 'Hardcoded string found')
  - (987, 'Line exceeds 80 characters')
  - (987, 'Hardcoded string found')
  - (988, 'Hardcoded string found')
  - (993, 'Hardcoded string found')
  - (994, 'Hardcoded string found')
  - (995, 'Line exceeds 80 characters')
  - (995, 'Hardcoded string found')
  - (996, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (1001, 'Hardcoded string found')
  - (1002, 'Line exceeds 80 characters')
  - (1002, 'Hardcoded string found')
  - (1003, 'Line exceeds 80 characters')
  - (1003, 'Hardcoded string found')
  - (1004, 'Hardcoded string found')
  - (1005, 'Hardcoded string found')
  - (1009, 'Hardcoded string found')
  - (1010, 'Hardcoded string found')
  - (1011, 'Line exceeds 80 characters')
  - (1011, 'Hardcoded string found')
  - (1012, 'Hardcoded string found')
  - (1013, 'Hardcoded string found')
  - (1015, 'Hardcoded string found')
  - (1016, 'Hardcoded string found')
  - (1020, 'Hardcoded string found')
  - (1021, 'Hardcoded string found')
  - (1022, 'Line exceeds 80 characters')
  - (1022, 'Hardcoded string found')
  - (1023, 'Hardcoded string found')
  - (1027, 'Hardcoded string found')
  - (1028, 'Hardcoded string found')
  - (1032, 'Hardcoded string found')
  - (1033, 'Hardcoded string found')
  - (1034, 'Line exceeds 80 characters')
  - (1034, 'Hardcoded string found')
  - (1035, 'Hardcoded string found')
  - (1036, 'Hardcoded string found')
  - (1040, 'Hardcoded string found')
  - (1041, 'Line exceeds 80 characters')
  - (1041, 'Hardcoded string found')
  - (1042, 'Line exceeds 80 characters')
  - (1042, 'Hardcoded string found')
  - (1043, 'Hardcoded string found')
  - (1044, 'Hardcoded string found')
  - (1048, 'Hardcoded string found')
  - (1049, 'Hardcoded string found')
  - (1050, 'Line exceeds 80 characters')
  - (1050, 'Hardcoded string found')
  - (1051, 'Hardcoded string found')
  - (1052, 'Hardcoded string found')
  - (1056, 'Hardcoded string found')
  - (1057, 'Line exceeds 80 characters')
  - (1057, 'Hardcoded string found')
  - (1058, 'Line exceeds 80 characters')
  - (1058, 'Hardcoded string found')
  - (1059, 'Hardcoded string found')
  - (1060, 'Hardcoded string found')
  - (1064, 'Hardcoded string found')
  - (1065, 'Line exceeds 80 characters')
  - (1065, 'Hardcoded string found')
  - (1066, 'Line exceeds 80 characters')
  - (1066, 'Hardcoded string found')
  - (1067, 'Hardcoded string found')
  - (1071, 'Hardcoded string found')
  - (1072, 'Hardcoded string found')
Issues in back-end/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in back-end/routes/auth.js:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in back-end/server.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
