### ISSUE TITLE
Issue-model vendor

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#21]
Automated Review Comments
Issues in back-end/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Line exceeds 80 characters')
  - (263, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Line exceeds 80 characters')
  - (284, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (289, 'Line exceeds 80 characters')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')
  - (324, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (346, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Line exceeds 80 characters')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Line exceeds 80 characters')
  - (369, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (380, 'Hardcoded string found')
  - (381, 'Line exceeds 80 characters')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Line exceeds 80 characters')
  - (413, 'Hardcoded string found')
  - (414, 'Line exceeds 80 characters')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
Issues in back-end/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in back-end/src/middleware/auth_middleware.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in back-end/src/models/vendor.ts:
  - (2, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in back-end/src/server.ts:
  - (6, 'Line exceeds 80 characters')
Issues in front-end/app/signup/page.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
