### ISSUE TITLE
Issue-feat: landing page updated

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#35]
Automated Review Comments
Issues in back-end/package-lock.json:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in back-end/src/models/user_model.ts:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
Issues in front-end/app/components/NavBar.tsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in front-end/app/landingPage/page.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in front-end/app/page.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
