### ISSUE TITLE
Issue-front-end integrate trying rn

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#40]
Automated Review Comments
Issues in back-end/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (200, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (204, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (261, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Line exceeds 80 characters')
  - (272, 'Hardcoded string found')
  - (273, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Line exceeds 80 characters')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Line exceeds 80 characters')
  - (294, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Line exceeds 80 characters')
  - (327, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Line exceeds 80 characters')
  - (354, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Line exceeds 80 characters')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Line exceeds 80 characters')
  - (383, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Line exceeds 80 characters')
  - (387, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Line exceeds 80 characters')
  - (402, 'Hardcoded string found')
  - (403, 'Line exceeds 80 characters')
  - (403, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (412, 'Hardcoded string found')
  - (413, 'Line exceeds 80 characters')
  - (413, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Line exceeds 80 characters')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Line exceeds 80 characters')
  - (432, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Line exceeds 80 characters')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Line exceeds 80 characters')
  - (455, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Line exceeds 80 characters')
  - (475, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (486, 'Line exceeds 80 characters')
  - (486, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Line exceeds 80 characters')
  - (497, 'Hardcoded string found')
  - (498, 'Line exceeds 80 characters')
  - (498, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Line exceeds 80 characters')
  - (502, 'Hardcoded string found')
  - (503, 'Line exceeds 80 characters')
  - (503, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (513, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (522, 'Line exceeds 80 characters')
  - (522, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Line exceeds 80 characters')
  - (526, 'Hardcoded string found')
  - (527, 'Line exceeds 80 characters')
  - (527, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (531, 'Line exceeds 80 characters')
  - (531, 'Hardcoded string found')
  - (532, 'Line exceeds 80 characters')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (541, 'Line exceeds 80 characters')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (545, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Line exceeds 80 characters')
  - (554, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (562, 'Line exceeds 80 characters')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (573, 'Line exceeds 80 characters')
  - (573, 'Hardcoded string found')
  - (574, 'Line exceeds 80 characters')
  - (574, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Line exceeds 80 characters')
  - (581, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (585, 'Line exceeds 80 characters')
  - (585, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (592, 'Hardcoded string found')
  - (593, 'Line exceeds 80 characters')
  - (593, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (604, 'Line exceeds 80 characters')
  - (604, 'Hardcoded string found')
  - (605, 'Line exceeds 80 characters')
  - (605, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (611, 'Hardcoded string found')
  - (612, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (623, 'Hardcoded string found')
  - (624, 'Line exceeds 80 characters')
  - (624, 'Hardcoded string found')
  - (625, 'Line exceeds 80 characters')
  - (625, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (629, 'Line exceeds 80 characters')
  - (629, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Line exceeds 80 characters')
  - (632, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (636, 'Line exceeds 80 characters')
  - (636, 'Hardcoded string found')
  - (637, 'Line exceeds 80 characters')
  - (637, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Line exceeds 80 characters')
  - (641, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (648, 'Line exceeds 80 characters')
  - (648, 'Hardcoded string found')
  - (649, 'Line exceeds 80 characters')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (655, 'Hardcoded string found')
  - (656, 'Line exceeds 80 characters')
  - (656, 'Hardcoded string found')
  - (657, 'Line exceeds 80 characters')
  - (657, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (669, 'Line exceeds 80 characters')
  - (669, 'Hardcoded string found')
  - (670, 'Line exceeds 80 characters')
  - (670, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (680, 'Hardcoded string found')
  - (682, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Line exceeds 80 characters')
  - (688, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (692, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (703, 'Line exceeds 80 characters')
  - (703, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (710, 'Line exceeds 80 characters')
  - (710, 'Hardcoded string found')
  - (711, 'Line exceeds 80 characters')
  - (711, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (715, 'Line exceeds 80 characters')
  - (715, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Line exceeds 80 characters')
  - (722, 'Hardcoded string found')
  - (723, 'Line exceeds 80 characters')
  - (723, 'Hardcoded string found')
  - (724, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (731, 'Line exceeds 80 characters')
  - (731, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (733, 'Line exceeds 80 characters')
  - (733, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (743, 'Hardcoded string found')
  - (744, 'Line exceeds 80 characters')
  - (744, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
Issues in back-end/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in front-end/app/components/Cards.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
Issues in front-end/app/components/NavBar.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
Issues in front-end/app/components/footer.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
Issues in front-end/app/page.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in front-end/app/signup/page.tsx:
  - (33, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (48, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
