### ISSUE TITLE
Issue-front end

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#5]
Automated Review Comments
Issues in front-end/.eslintrc.json:
  - (3, 'Hardcoded string found')
Issues in front-end/.gitignore:
  - (2, 'Line exceeds 80 characters')
Issues in front-end/README.md:
  - (2, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in front-end/app/components/Cards.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
Issues in front-end/app/components/NavBar.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in front-end/app/components/footer.tsx:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in front-end/app/layout.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in front-end/app/login/page.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in front-end/app/page.tsx:
  - (3, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in front-end/next.config.mjs:
  - (2, 'Hardcoded string found')
Issues in front-end/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in front-end/public/next.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in front-end/public/vercel.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in front-end/store/useAuthStore.ts:
  - (2, 'Hardcoded string found')
Issues in front-end/styles/custom-colors.module.css:
  - (28, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
Issues in front-end/tailwind.config.ts:
  - (2, 'Hardcoded string found')
Issues in front-end/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
