### ISSUE TITLE
Issue-wowwwwwwwwwww

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/plan-hour#7]
Automated Review Comments
Issues in back-end/models/Photographer.ts:
  - (2, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in back-end/package-lock.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in back-end/package.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in front-end/app/components/Cards.tsx:
  - (9, 'Line exceeds 80 characters')
Issues in front-end/app/page.tsx:
  - (14, 'Hardcoded string found')
Issues in front-end/app/signup/page.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
Issues in front-end/package-lock.json:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in front-end/styles/custom-colors.module.css:
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
